export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const PROFILEIMGUPDATE = "PROFILEIMGUPDATE";
export const PROFILEDETAILSUPDATE = "PROFILEDETAILSUPDATE";

export const RESET_EDITOR = "RESET_EDITOR";
export const SET_EDITOR_STATE = "SET_EDITOR_STATE";
export const TEXT_UPSERT = "TEXT_UPSERT";
export const SET_ACTIVE_OBJ = "SET_ACTIVE_OBJ";
export const SET_ACTIVE_TRACK = "SET_ACTIVE_TRACK";

export const DELETE_OBJ = "DELETE_OBJ";
export const UPSERT_EDITOR_BG_COLOR = "UPSERT_EDITOR_BG_COLOR";
export const UPSERT_EDITOR_BG_IMAGE = "UPSERT_EDITOR_BG_IMAGE";
export const UPSERT_EDITOR_BG_VIDEO = "UPSERT_EDITOR_BG_VIDEO";
export const UPSERT_EDITOR_BGS = "UPSERT_EDITOR_BGS";
export const EDTR_REFRESH_DURATION = "EDTR_REFRESH_DURATION";

export const IMAGE_UPSERT = "IMAGE_UPSERT";
export const FXS_UPSERT = "FXS_UPSERT";
export const AUDIO_UPSERT = "AUDIO_UPSERT";
export const GRAPHIC_UPSERT = "GRAPHIC_UPSERT";

export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";

export const SET_ANIMATION = "SET_ANIMATION";

export const SET_FILE_UPLOAD = "SET_FILE_UPLOAD";

export const SET_AUDIO_TRIM_SETTING = "SET_AUDIO_TRIM_SETTING";

export const UPDATE_LAYERS = "UPDATE_LAYERS";
export const UPDATE_LAYOUT = "UPDATE_LAYOUT";
export const HIDE_SHOW_LOADER = "HIDE_SHOW_LOADER";
export const RESET_COMMON_DATA = "RESET_COMMON_DATA";
export const UPSERT_TAB_ASSETS = "UPSERT_TAB_ASSETS";

export const CLONE_DUPLICATE = "CLONE_DUPLICATE";

/* ************************ Admin Types **************************** */
